config/routes.rb
Rails.application.routes.draw do
  get 'home/zipcode'
  root 'home#index'

  post "zipcode" => 'home#zipcode'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=46217&distance=25&API_KEY=B6E22567-7838-48DE-BED3-36028925B7A9'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response) 

# Checks for empty return results.
    if @output.empty?
      @final_output = "error"
    elsif !@output
      @final_output = "error"
      else
        @final_output = @output[0]['AQI']
    end

    if @final_output == "error"
      @api_color = "gray"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = " Safe (0-50): Air quality is satisfactory. Air pollution is little to none."
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_description = "Moderate (51-100): Air quality is acceptable; for some pollutants there may be a moderate health concern for those sensitive to air pollution."
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
      @api_description = "Warning (101-150): General public is not likely to be affected. People with lung disease, older adults, and children are at greater risk to ozone exposure."
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
      @api_description = "Unhealthy (151-200): Everyone may experience health effects. Members of sensitive groups may experience more severe health effects. "
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "purple"
      @api_description = "Very Unhealthy (201-300): Everyone may experience more serious health effects."
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = "maroon"
      @api_description = "Hazardous (301-500): Emergency conditions. The entire population is likely to be affected."
    end
  end

  def zipcode
    @zip_query = params[:zipcode]
    if @zip_query = params[:zipcode] == ""
      @zip_query = "ERROR: NO ZIPCODE ENTERED"
    elsif @zip_query = params[:zipcode]
     
require 'net/http'
    require 'json'

    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query +'&distance=25&API_KEY=B6E22567-7838-48DE-BED3-36028925B7A9'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response) 

# Checks for empty return results.
    if @output.empty?
      @final_output = "error"
    elsif !@output
      @final_output = "error"
      else
        @final_output = @output[0]['AQI']
    end

    if @final_output == "error"
      @api_color = "gray"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = " Safe (0-50): Air quality is satisfactory. Air pollution is little to none."
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_description = "Moderate (51-100): Air quality is acceptable; for some pollutants there may be a moderate health concern for those sensitive to air pollution."
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
      @api_description = "Warning (101-150): General public is not likely to be affected. People with lung disease, older adults, and children are at greater risk to ozone exposure."
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
      @api_description = "Unhealthy (151-200): Everyone may experience health effects. Members of sensitive groups may experience more severe health effects. "
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "purple"
      @api_description = "Very Unhealthy (201-300): Everyone may experience more serious health effects."
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = "maroon"
      @api_description = "Hazardous (301-500): Emergency conditions. The entire population is likely to be affected."
    end







    end
   end   
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Weatherflan", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      <%= form_tag home_zipcode_path, :method => 'GET' do %>
        <%= text_field_tag 'zipcode', nil, placeholder: "Enter Zipcode", class: "form-control me-2" %>
        <%= submit_tag 'Search', class: 'btn btn-outline-dark' %>
       
 <% end %>

    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="container-fluid <%= @api_color %> text-light p-5">
    <div class="container-sm">
<center> <img src="https://static.thenounproject.com/png/395161-200.png" class="rounded" alt="..."> </center>
</div>
    <div class="container bg-dark p-5">
        <h1 class="display-4">Welcome to Weatherflan Home</h1>
        <hr>
        <p>Weather application built in Rails 7. Press "reload" in your web browser to update the reading.</p>
        <p> <%= @api_description %> </p>
        <a href="#" class="btn <%= @api_color %>"> The current ozone air quality reading in Indianapolis, IN is <%= @final_output %></a>
    </div>
</div>

app/views/home/zipcode.html.erb
<div class="container-fluid <%= @api_color %> text-light p-5">
	<center> <img src="https://static.thenounproject.com/png/395161-200.png" class="rounded" alt="..."> </center>
    <div class="container bg-dark p-5">
        <h1 class="display-4">Weatherflan Zipcode Search</h1>
        <hr>
        <p>Weather application built in Rails 7. Press "reload" in your web browser to update the reading.</p>
        <p> <%= @api_description %> </p>
        <a class="card <%= @api_color %>"> The current ozone air quality in Zip Code <%= @zip_query %> is <%= @final_output %>.</a>
    </div>
</div>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weatherflan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class ="container">
    </br>
    <%= yield %>
  </div>
  </body>
</html>